/**
 * Pulse data service — loads run records and reports from static JSON files.
 *
 * Data layout (in public/data/):
 *   data/runs-index.json          — array of RunRecord summaries
 *   data/runs/{iso_week}.json     — full RunRecord per week
 *   data/reports/{iso_week}.json  — PulseReport per week
 *
 * These files are generated by the pipeline CLI:
 *   python -m pulse.cli export-frontend
 *
 * For local development, the mock data generator creates them too.
 */

import type { RunRecord, PulseReport, DashboardSummary } from '@/types';

const BASE = '/data';

async function fetchJson<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(`${BASE}${path}`);
    if (!res.ok) return null;
    return (await res.json()) as T;
  } catch {
    return null;
  }
}

export const api = {
  /** List all runs (newest first). */
  async getRuns(): Promise<RunRecord[]> {
    const index = await fetchJson<RunRecord[]>('/runs-index.json');
    return index ?? [];
  },

  /** Get a single run by ISO week. */
  async getRun(isoWeek: string): Promise<RunRecord | null> {
    return fetchJson<RunRecord>(`/runs/${isoWeek}.json`);
  },

  /** Get the PulseReport for a given week. */
  async getReport(isoWeek: string): Promise<PulseReport | null> {
    return fetchJson<PulseReport>(`/reports/${isoWeek}.json`);
  },

  /** Compute dashboard summary from all available runs. */
  async getDashboardSummary(): Promise<DashboardSummary> {
    const runs = await this.getRuns();

    if (runs.length === 0) {
      return {
        total_runs: 0,
        successful_runs: 0,
        failed_runs: 0,
        avg_duration_ms: 0,
        total_reviews_processed: 0,
        last_run_at: null,
        current_week: getCurrentISOWeek(),
      };
    }

    const successful = runs.filter((r) => r.status === 'completed');
    const failed = runs.filter((r) => r.status === 'failed');

    // Average duration of completed runs
    const durations = successful.map((r) => {
      return Object.values(r.stages).reduce(
        (sum, s) => sum + (s.duration_ms ?? 0),
        0
      );
    });
    const avgDuration =
      durations.length > 0
        ? Math.round(durations.reduce((a, b) => a + b, 0) / durations.length)
        : 0;

    const totalReviews = runs.reduce(
      (sum, r) => sum + (r.ingest?.review_count ?? 0),
      0
    );

    // Most recent run (already sorted newest-first by the index)
    const lastRun = runs[0];

    return {
      total_runs: runs.length,
      successful_runs: successful.length,
      failed_runs: failed.length,
      avg_duration_ms: avgDuration,
      total_reviews_processed: totalReviews,
      last_run_at: lastRun.completed_at ?? lastRun.updated_at,
      current_week: getCurrentISOWeek(),
    };
  },
};

/** Current ISO week string, e.g. "2026-W25". */
function getCurrentISOWeek(): string {
  const now = new Date();
  const iso = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
    .toISOString()
    .slice(0, 10);
  const d = new Date(iso);
  const year = d.getUTCFullYear();
  const jan1 = new Date(Date.UTC(year, 0, 1));
  const week = Math.ceil(
    ((d.getTime() - jan1.getTime()) / 86400000 + jan1.getUTCDay() + 1) / 7
  );
  return `${year}-W${String(week).padStart(2, '0')}`;
}
